### ISSUE TITLE
Link to install.tar.gz is not valid

### ISSUE THREAD

**Issue by nunix** [sirredbeard/WLinux#1]
Not sure if I missed something, but when clicking on the install.tar.gz for the nightly build, it gives me a OneDrive error.

**Comment by sirredbeard** [comment]
I will update with a new build.

The .tar.gz nightly builds are offered as a convenience, I will try my best to offer them, but that is what the build image script is for.

You can use the build script on any existing Debian or WLinux distro.

**Comment by sirredbeard** [comment]
Fixed. I also changed where those images were stored so there is less likely to be breakage in the future. Thank you for your issue report!
