### ISSUE TITLE
Script for installing google chrome installs a buggy version of Chrome

### ISSUE THREAD

**Issue by CaptainJawZ** [sirredbeard/WLinux#1]
Hello! I'm a bit new with Linux in general, let alone WLS, I already set up x410 as suggested, and used the script sudo /opt/installchrome.sh to install google chrome however when opening it this is what I see: 
![image](https://user-images.githubusercontent.com/43111068/45923074-82e72a80-bea1-11e8-8e51-3e25560edf59.png)

Thank you in advance for any support!

**Comment by sirredbeard** [comment]
Tracking here:

https://github.com/WhitewaterFoundry/WLinux/issues/37
