### ISSUE TITLE
Repository error: https://apt.patrickwu.ml stretch Release

### ISSUE THREAD

**Issue by nunix** [sirredbeard/WLinux#3]
After the install, the first apt-get update will throw this error about the repository https://apt.patrickwu.ml stretch Release
![image](https://user-images.githubusercontent.com/905874/44151506-12a060dc-a0a3-11e8-98d1-73b103e57eb5.png)

**Comment by patrick330602** [comment]
I think this is the issue from my side... He included the old installation code for wslu, [this is the proper one.](https://github.com/patrick330602/wslu#for-ubuntudebiankali-linux)

**Comment by sirredbeard** [comment]
I originally included wslu in the image itself but it complicated things too much for 1.0, so I moved it to its own install script for now. I forgot to remove the wslu repo from the built-in sources.list, which I went ahead and fixed. The new install script handles wslu install properly per @patrick330602's link.
